### ISSUE TITLE
handyport: Where we are and where we are going to

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/cawbird#1]
*The primary purpose of this issue is to discuss a few things with @IBBoard as the maintainer of upstream Cawbird.*

---

Alright, since I am now through with a third of my work, let's summarize where I am and what the next steps are.

## What I have done

Right now, I have been working on a lot of things around the MainWidget, so to summarize:

- [x] SettingsDialog itself has a libhandy-enabled design.
- [x] Snippets can be managed with a libhandy-design.
- [x] New AboutDialog (even if this is not a necessity).
- [x] Create a new Account has a libhandy-design.
- [ ] MainWindow was partially redesigned.
- [ ] Account Settings are partially done.

Any new interface has been designed with Glade and UI-Files, which should make it easier for future contributors to work on the interface and also enables us to have a cleaner source code.

So, after hitting a bug (as we were not actually saving the website when editing it), I have decided to take a dive into the current backend to discover it is written in C... And also being written in a quite confusing way, if you ask me.
Since I also want to introduce new features, I thought about rewriting the backend back to Vala and [created an idea of how to reimplement](https://github.com/CodedOre/cawbird/issues/2), however I have my problems finding a good starting point for that work.

## What is to be done

Well, after looking on where I am currently, let's think about my next steps:

- [ ] **New widget for text entry**
So, the idea here is to update the current widget for multi-line text entry with an progress indicator of how much space is still available, most likely in the style of how Twitter itself do it:
![tweet-fill-demo](https://user-images.githubusercontent.com/47981497/99381828-e7f50a00-28cb-11eb-8e12-6dc9630767c9.gif)
The difficulty here lies in the fact that we don't have a circular progress, meaning this would need to be handcrafted.
- [ ] **Finalize Account Settings**
Currently missing are: Image Control, Description (as widget for it is still to be redesigned) and filters.
- [ ] **Add Keyboard Shortcut dialog**
What stopped me from including it for now was the fact that it seems to be not compatible with Glade, so that went down my priority list.
- [ ] **Rewrite MainWindow**
MainWindow is currently the only interface where I only modified the source code, rather than rewriting it with the integration of a UI-File in mind, but that brings up some problems. As I also plan to make a switch from GtkWindow to HdyWindow (in order to easily add CreateAccountWidget when needed) which seems to break the current code, I think it will make sense to redo this source code as well.
- [ ] **Replace MainWidget through seperated widget**
The current MainWidget incorporate a lot of features, from all view up to the navigation between them. This however make it harder to be implemented in the new layout, where the navigation is split from the content. So, the goal is to replace MainWidget with seperated widgets handling only one view at a time.
- [ ] **New content view**
Well, one of my main ideas for the new UI was to have a better view for threads, so we should have this point in the list.
- [ ] **New Media Widget**
Implement a new Widget to display media, allowing for having controls for the media.
- [ ] **Implement new CreateTweetWidget**
Or maybe widgets, as we have to seperated cases with different context.
- [ ] **Add Accessibility back**
Currently I do not have included Accessibility, as my current focus lies in implementing the interface first. But given the fact I use exclusively UI-files (for now), this should not be a big task to do.

---

So, extensive summary completed.

**Comment by IBBoard** [comment]
Just compiled and run the latest version. It looks like it is coming along well. It's not all how I'd design it myself, but 

*  SettingsDialog itself has a libhandy-enabled design
   * Does the example tweet need fixing? I can't see the toggles changing anything at the moment
   * There's not much on the Details or Options sections of the account details. Is it worth combining them? Or will it be too much when we have the description in?
   * Minor inconsistency: Deleting a snippet uses "-" but deleting an account uses the bin icon
   * also, I don't know if there's a better option for the delete options - having the label on the left and the small button on the right seems a bit odd, because it's not an option like the others, plus having it under another widget makes it prone to being accidentally clicked on
   * Is the search an automatic integrated feature, or do we need to do special things for each bit?
* Snippets can be managed with a libhandy-design.
   * Looks good
*  New AboutDialog (even if this is not a necessity).
   * I'm not convinced by the bottom of the dialog (the "Application" and "Version" section) but if that's the LibHandy way then I guess we need to be consistent
   * Presumably we need to define all of our translators somewhere!
* Create a new Account has a libhandy-design.
   * It integrates well with the dialog, but I'm not convinced by the page indicators at the bottom. Indicators like that make me assume that I can manually swap between pages. But I can't.
* Account Settings are partially done.
   * I assume some that's why bits like filters don't work
* New widget for text entry
   * I can see why Twitter don't show numbers when weighting isn't consistent. But also, weighting isn't consistent so it's just as inconsistent when we get to the end.
   * Reimplementing it shouldn't be too hard as a custom Cairo paint function
   * I'm happy with the numbers and giving users more info
* Rewrite MainWindow / MainWindow was partially redesigned.
   * The buttons don't seem to appear at the bottom yet for "narrow" windows (which includes my normal width!)
   * I lose some of the text on "Direct Messages" when the buttons first appear, but that appears to be because of my theme. Adwaita has smaller (too small?) text.
   * Has "Compose" become a toggle rather than an action?
   * Just as a reminder, search isn't working yet (it's not anywhere else on your list)
   * It looks like I need to update my custom "Adwaita Dark Green" theme because the buttons are all too tall, but it doesn't happen in vanilla Adwaita
   * Maybe it's just a GTK/Adwaita thing, but the settings menu looks a bit odd. The light list on the darker background looks like we're using the wrong widgets (they're not meant to be in a menu) and the narrow margin doesn't help.
   * The account indicator works well, but I wonder whether we're missing out by not having something always visible to know which account your app is on (not that I can suggest where to put it)
* Replace MainWidget through seperated widget
   * I thought MainWidget was mostly a container. Everything it does for navigation should be replaced by libhandy functionality, and I thought we might even be able to remove it entirely.
   * `switch_page()` and other navigation functions are all over the code, but can we end up just find and replacing them with the new method?
* New content view
   * Would it make sense to release an initial version with the existing content views within libhandy containers and then replace it with a new design after that?
* New Media Widget
   * This is probably a good opportunity to replace C code with Vala. But be careful because there's some oddities with some of the widgets because of what we need them to do (e.g. scaling code)
* Implement new CreateTweetWidget
   * What are the different contexts? Do you mean tweet vs reply vs quote? The current approach of a main input and then having the tweet above (or below for quoting) seems sensible and reduces the possibility of bugs with duplicate code.
* Add Accessibility back
   * Yeah, sorry, but having ignored the a18y community for a while and had some accessibility bugs then I won't merge this until we're in an equivalent place on accessibility 🙂

I noticed you mentioned Glade and UI files a few times. I've never bothered using Glade for Cawbird (too many widgets refused to work and I can just hack the XML) but we should already be using UI files for 90%+ of the main widgets. I don't know why Baedert didn't use it for a few bits. Is there something else that I missed?

I'm not surprised that some bits (like the main window and widget) require some code rewriting, though. There's a few assumptions baked in to how the app is built.

**Comment by CodedOre** [comment]
> Does the example tweet need fixing? I can't see the toggles changing anything at the moment

The example tweet is currently a placeholder. Since I don't know right now if I possible change a few things in the TweetListEntry I wanted to add this back when I am at that point.

> There's not much on the Details or Options sections of the account details. Is it worth combining them? Or will it be too much when we have the description in?

Well, the details page is still missing the avatar and banner additionally to the description. And as "delete" and "open at startup" are quite different to details I thought of splitting these sections. 

> Minor inconsistency: Deleting a snippet uses "-" but deleting an account uses the bin icon

Right, will probably go for a bin at both points.

> also, I don't know if there's a better option for the delete options - having the label on the left and the small button on the right seems a bit odd, because it's not an option like the others, plus having it under another widget makes it prone to being accidentally clicked on

Well, I think I will make a small space between the widgets above in the Snippets Page. For accounts I think it is not a problem, as it has an confirmation before actually deleting it.

> Is the search an automatic integrated feature, or do we need to do special things for each bit?

`HdyPreferencesWindow` adds the search automatically for all elements in an `HdyPreferencesGroup`.

> New AboutDialog (even if this is not a necessity).
> - I'm not convinced by the bottom of the dialog (the "Application" and "Version" section) but if that's the LibHandy way then I guess we need to be consistent
> - Presumably we need to define all of our translators somewhere!

Actually this is a special implementation following [this mockup from the Gnome team](https://gitlab.gnome.org/Teams/Design/os-mockups/-/blob/master/about-dialogs/about-dialogs.png), as far as I know this is the only implementation so far...

> Create a new Account has a libhandy-design.
> - It integrates well with the dialog, but I'm not convinced by the page indicators at the bottom. Indicators like that make me assume that I can manually swap between pages. But I can't.

Thought it would be good to show the user progress using the indicators, similar to Gnome Tours or the Greeter of Elementary. However, I might have to made it a little bit clearer this is actually not interactive.

> Account Settings are partially done.
> - I assume some that's why bits like filters don't work

That's right. I am missing filters and the missing detail elements. Also have to take a look if we already have a list of blocked account I can easily show or if this needs to be added.

> New widget for text entry
> - I can see why Twitter don't show numbers when weighting isn't consistent. But also, weighting isn't consistent so it's just as inconsistent when we get to the end.
> - Reimplementing it shouldn't be too hard as a custom Cairo paint function
> - I'm happy with the numbers and giving users more info

That means? "Go for it" or "Keep it like it is"?

> Rewrite MainWindow / MainWindow was partially redesigned.
> - The buttons don't seem to appear at the bottom yet for "narrow" windows (which includes my normal width!)

Well, MainWidget currently overrides **anything** below the titlebar when added... Technically they are there...

> I lose some of the text on "Direct Messages" when the buttons first appear, but that appears to be because of my theme. Adwaita has smaller (too small?) text.

If you look [at the mockup](https://github.com/IBBoard/cawbird/issues/177), I would likely add a function shortening the text to "DM's" when it is small. Not implemented yet.

> Has "Compose" become a toggle rather than an action?
> Just as a reminder, search isn't working yet (it's not anywhere else on your list)

A lot does not work or is finalized in MainWindow...

> Maybe it's just a GTK/Adwaita thing, but the settings menu looks a bit odd. The light list on the darker background looks like we're using the wrong widgets (they're not meant to be in a menu) and the narrow margin doesn't help.

`GtkListBox` seems to add the light theme at any time it is used. Have to look if I can replace it with an `GtkBox` without loosing the functionality (as activating a row is trigger by a signal from the ListBox rather than the row).

> The account indicator works well, but I wonder whether we're missing out by not having something always visible to know which account your app is on (not that I can suggest where to put it)

I actually have an idea which would move the Account selection to an toggled sidebar with an `HdyLeaflet` and only showing the Back Button when you can actually go back. See [this mockup](https://twitter.com/CodedOre/status/1328801103253745669)

Benefits: It would be better usable on mobile (as `HdyLeaflet` could give us a nice swipe gesture) and we get back an account button where we can place our current account picture.

However, it is unnecessarily for only one account and `HdyActionRow` makes problems when placed inside an `GtkRevealer`, so might not actually work...

> New content view 
> - Would it make sense to release an initial version with the existing content views within libhandy containers and then replace it with a new design after that?

I don't know if the sub-views of MainWidget are already usable seperated. If yes, than this would be possible, if no, I have to do it directly when I remove MainWidget.

> What are the different contexts? Do you mean tweet vs reply vs quote? The current approach of a main input and then having the tweet above (or below for quoting) seems sensible and reduces the possibility of bugs with duplicate code.

I mean tweet vs reply vs quote. 

> Add Accessibility back
> - Yeah, sorry, but having ignored the a18y community for a while and had some accessibility bugs then I won't merge this until we're in an equivalent place on accessibility slightly_smiling_face

Understandably.

> I noticed you mentioned Glade and UI files a few times. I've never bothered using Glade for Cawbird (too many widgets refused to work and I can just hack the XML) but we should already be using UI files for 90%+ of the main widgets. I don't know why Baedert didn't use it for a few bits. Is there something else that I missed?

Yes, there are already a lot of UI-Files, however I want to bring it from 90% to 100% (or at least 99%).

**Comment by IBBoard** [comment]
>>    New widget for text entry
>>
>>   *    I can see why Twitter don't show numbers when weighting isn't consistent. But also, weighting isn't consistent so it's just as inconsistent when we get to the end.
>>   *     Reimplementing it shouldn't be too hard as a custom Cairo paint function
>>   *    I'm happy with the numbers and giving users more info
>
>That means? "Go for it" or "Keep it like it is"?

Keep it as is for now.

> I actually have an idea which would move the Account selection to an toggled sidebar with an HdyLeaflet and only showing the Back Button when you can actually go back. See this mockup

So we only see the back button when one of the Hdy panels has slid over the top? Interesting. It might work. But we need to make sure that we're not losing other functionality or making interaction harder.

> I don't know if the sub-views of MainWidget are already usable seperated. If yes, than this would be possible, if no, I have to do it directly when I remove MainWidget.

Apart from navigation then I think it's fine. And a lot of the "click a link and open a tweet in the TweetInfoView" code is in the utils URL handling anyway.
