### ISSUE TITLE
A discussion of a new backend

### ISSUE THREAD

**Issue by CodedOre** [CodedOre/cawbird#2]
*The primary purpose of this issue is to discuss a few things with @IBBoard as the maintainer of upstream Cawbird.*

---

So, as I have taken a look inside the current backend code, I have found the following things: It is written in C, and it is has a few things I think are a little bit confusing, like MiniTweet vs. Tweet, etc.

So, as @IBBoard already said he would like to rewrite the backend in Vala, I have put together an idea how I would rewrite it.

This is a basic plan on how it should generally be build up, if I am going to rewrite the backend back to Vala:

> # Classes
>
> 
> ## Utils
> 
> ```c#
> public class Utils
> ```
> 
> A static class containing general methods and fields used from the other classes.
> 
> ### Creation Methods
> 
> ```c#
> public static Utils @get ()
> ```
> 
> Creates one static instance of Utils, or returns the existing one.
> 
> ### Methods
> 
> ```c#
> public Json.Node call_api (Account account, string api_call)
> ```
> 
> Calls the Twitter API with the wanted call as string argument. Returns response as json node.
> 
> ```c#
> public void send_notification ()
> ```
> 
> Gets notification from the accounts and sends them to the system.
> 
> ### Signals
> 
> ```c#
> public signal void reached_limit (bool locked, int wait_time)
> ```
> 
> Is emitted when the rate limit is exceeded (with `true` and the remaining time as `int`), or when the rate limit is reset (with `false`). Mostly called from `call_api` when error 88 is returned.
> 
> ### Fields
> 
> ```c#
> private string oauth_key
> ```
> 
> The key used to identify Cawbird to Twitter.
> 
> ```c#
> private string oauth_secret
> ```
> 
> The secret used to identify Cawbird to Twitter.
> 
> ---
> 
> ## User
> 
> ```c#
> public class User
> ```
> 
> A class to store information about a user.
> 
> ### Creation Methods
> 
> ```c#
> public User.from_id (string user_id)
> ```
> 
> Get user with given user_id. Calls `GET /2/users`.
> 
> ```c#
> public User.from_json (Json.Node node)
> ```
> 
> Parses a given json node to an new user object.
> 
> ### Methods
> 
> ```c#
> public update_user.from_json (Json.Node node)
> ```
> 
> Updates user information from a json node.
> 
> ### Signals
> 
> ```c#
> public signal void user_data_updated ()
> ```
> 
> Emitted when user information was updated.
> 
> ### Fields
> 
> ```c#
> public string user_id
> ```
> 
> The unique identifier for this user.
> 
> ```c#
> public string user_name
> ```
> 
> The user name of this user.
> 
> ```c#
> public string screen_name
> ```
> 
> The twitter handle of this user.
> 
> ```c#
> public bool protected_account
> ```
> 
> If this user is protected in Twitter.
> 
> ```c#
> public bool verified
> ```
> 
> If this user is verified by Twitter.
> 
> ```c#
> public string url
> ```
> 
> The URL of this user's profile.
> 
> ```c#
> public string description
> ```
> 
> The description of this user's profile.
> 
> ```c#
> public bool verified
> ```
> 
> Indicate if this user is a verified Twitter user.
> 
> ```c#
> public int follower_count
> ```
> 
> The number of users following this user.
> 
> ```c#
> public int friends_count
> ```
> 
> The number of users this user follows.
> 
> ```c#
> public User[] friends
> ```
> 
> All users who are friends to this user. In other words: All users this user follows.
> 
> ```c#
> public User[] followers
> ```
> 
> All users who are following this user.
> 
> ```c#
> public int tweet_count
> ```
> 
> The number of tweets this user posted.
> 
> ```c#
> public Tweet pinned_tweet
> ```
> 
> A references to the tweet that the user pinned.
> 
> ---
> 
> ## Account
> 
> ```c#
> public class Account : User
> ```
> 
> A class to store information about a logged in user.
> 
> ### Creation Methods
> 
> ```c#
> public Account.from_data (string account_id)
> ```
> 
> Loads an existing account from the database.
> 
> ```c#
> public Account.log_in (int pin)
> ```
> 
> Create a new account from a pin gained by `CreateAccountWidget`.
> 
> ### Methods
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public OAuthProxy proxy
> ```
> 
> The proxy with the personal keys and secrets used to authenticated an api call to Twitter.
> 
> ```c#
> public User[] blocked
> ```
> 
> All users blocked by this account.
> 
> ```c#
> public User[] muted
> ```
> 
> All users muted by this account.
> 
> ```c#
> public Filter[] filters
> ```
> 
> Any filter this user has.
> 
> ---
> 
> ## Filter
> 
> ```c#
> public class Filter
> ```
> 
> A class storing information about a filter of tweets.
> 
> ### Creation Methods
> 
> ```c#
> public Filter (string expr)
> ```
> 
> Creates an Filter with an given expression.
> 
> ### Methods
> 
> ```c#
> public bool matches (string text)
> ```
> 
> Returns true if the text matches the expression.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public int id
> ```
> 
> The id given for this filter.
> 
> ```c#
> public string expression
> ```
> 
> The regular expression.
> 
> ```c#
> private string description
> ```
> 
> An description of this filter.
> 
> ### 
> 
> ---
> 
> ## TextEntity
> 
> ```c#
> public class TextEntity
> ```
> 
> A class storing information about click able entities in a text.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ```c#
> public TextEntity.from_json (Json.Node)
> ```
> 
> Create a new TextEntity by parsing a given json node.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public string display_text
> ```
> 
> The string that is displayed in the string.
> 
> ```c#
> public int text_start
> ```
> 
> The point where the entity starts in the text.
> 
> ```c#
> public int text_end
> ```
> 
> The point where the entity stops in the text.
> 
> ```c#
> public string full_text
> ```
> 
> The string of the complete text of the entity. Used for the tooltip as well.
> 
> ---
> 
> ## Tweet
> 
> ```c#
> public class Tweet
> ```
> 
> A class storing information about an single tweet.
> 
> ### Creation Methods
> 
> ```c#
> public Tweet.from_id (string id)
> ```
> 
> Create a new tweet object using it's id, calling additional information over the API.
> 
> ```c#
> public Tweet.from_json (Json.Node node)
> ```
> 
> Create a new tweet object by parsing an given json node.
> 
> ### Methods
> 
> ```c#
> public void update.from_json (Json.Node node)
> ```
> 
> Updates fields from a Json node.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public string id
> ```
> 
> The unique identifier for this tweet.
> 
> ```c#
> public string text
> ```
> 
> The text this tweet contains.
> 
> ```c#
> public TweetType type
> ```
> 
> The kind of tweet this is.
> 
> ```c#
> public TweetState state
> ```
> 
> The state this tweet is.
> 
> ```c#
> public TextEntity[] text_entities
> ```
> 
> Entities found by Twitter in the text of this tweet.
> 
> ```c#
> public User author
> ```
> 
> The author who created this tweet.
> 
> ```c#
> public GLib.Date creation_date
> ```
> 
> The date the tweet was created.
> 
> ```c#
> public Thread thread
> ```
> 
> The thread this tweet is part of.
> 
> ```c#
> public User[] replied_users
> ```
> 
> All users this tweet replies to.
> 
> ```c#
> public Media[] media
> ```
> 
> Media attached to this tweet.
> 
> ```c#
> public Poll[] polls
> ```
> 
> Polls attached to this tweet.
> 
> ```c#
> public int retweeted_count
> ```
> 
> How often this tweet was retweeted.
> 
> ```c#
> public int quoted_count
> ```
> 
> How often this tweet was quoted.
> 
> ```c#
> public int liked_count
> ```
> 
> How often this tweet was liked.
> 
> ```c#
> private Tweet? outside_source
> ```
> 
> If this tweet is a retweet or quote, this is the original tweet. Is null if this is not a retweet.
> 
> ---
> 
> ## Thread
> 
> ```c#
> public class Thread
> ```
> 
> A container storing all tweets of an conversation.
> 
> ### Creation Methods
> 
> ```c#
> public Conversation (string conversation_id)
> ```
> 
> Create a new conversation object from an id and loads all tweets.
> 
> ### Methods
> 
> ```c#
> public void call_all_tweets ()
> ```
> 
> Calls all tweets from the Twitter server.
> 
> ```c#
> public void call_new_tweets ()
> ```
> 
> Check if new tweets exists, and pulls them from the Twitter server.
> 
> ```c#
> public void update_metrics ()
> ```
> 
> Calls the Twitter Servers to receives updated metrics for included Tweets.
> 
> ```c#
> public Tweet[] list_replies (Tweet tweet)
> ```
> 
> Returns a list of all tweets replying to given tweet.
> 
> ```c#
> public Tweet[] list_thread (Tweet first_tweet)
> ```
> 
> Returns a list of tweets for display as a thread. When the thread branches, prefer tweets where previous mentioned people reply and those which are going deeper.
> 
> ```c#
> public Tweet get_parent_tweet (Tweet tweet)
> ```
> 
> Returns the tweet that the tweet in the argument replied to.
> 
> ### Fields
> 
> ```c#
> public string id
> ```
> 
> The unique identifier for this conversation.
> 
> ```c#
> private GLib.Node thread_node
> ```
> 
> The first tweet of this conversation. As we are using `GLib.Node`, we can jump to any tweet in this conversation.
> 
> ---
> 
> ## Tweetline
> 
> ```c#
> public interface Tweetline
> ```
> 
> A interface managing a list of tweets.
> 
> Compared to `Conversation`, this class is used to manage tweets without direct relationship, such as in lists or the home timeline.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ```c#
> public abstract void update_tweets ()
> ```
> 
> Pulls new tweets from the Twitter API and appends them to the list.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> private Tweet[] tweet_list
> ```
> 
> A reverse chronological ordered list of all tweets in this Tweetline.
> 
> ---
> 
> ## List
> 
> ```c#
> public class List : Tweetline
> ```
> 
> A class managing a list created by a user.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ### Signals
> 
> ### Fields
> 
> ---
> 
> ## Timeline
> 
> ```c#
> public class Timeline : Tweetline
> ```
> 
> The timeline of tweet from a specific user.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ### Signals
> 
> ### Fields
> 
> ---
> 
> ## Media
> 
> ```c#
> public class Media
> ```
> 
> A base for all media-related classes.
> 
> ### Creation Methods
> 
> ```c#
> public Media.from_json (Json.Node node)
> ```
> 
> Create a new media object by parsing an given json node.
> 
> ### Methods
> 
> ```c#
> public abstract async void load_lowres ()
> ```
> 
> Loads the low resolution media from the url.
> 
> ```c#
> public abstract async void low_hires ()
> ```
> 
> Loads the high resolution media from the url.
> 
> ### Signals
> 
> ```c#
> public signal void lowres_loaded ()
> ```
> 
> Emitted when low resolution media was loaded.
> 
> ```c#
> public signal void hires_loaded ()
> ```
> 
> Emitted when high resolution media was loaded.
> 
> ### Fields
> 
> ```c#
> public string id
> ```
> 
> The unique identifier for this media object.
> 
> ```c#
> public MediaType type
> ```
> 
> The type of media this is.
> 
> ```c#
> public int width
> ```
> 
> The width of the media.
> 
> ```c#
> public int height
> ```
> 
> The height of the media.
> 
> ```c#
>  public string alt_text
> ```
> 
> An text added as description to the media object.
> 
> ```c#
> public string preview_url
> ```
> 
> The url for the preview image.
> 
> ```c#
> public string media_url
> ```
> 
> The url where the media is stored.
> 
> ```c#
> public Cairo.ImageSurface preview_surface
> ```
> 
> The preview_image for this media. Used in a tweet overview.
> 
> ---
> 
> ## Video
> 
> ```c#
> public class Video : Media
> ```
> 
> A class storing a video from twitter.
> 
> Displayed in `MediaWidget` with full playback control.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ```c#
> public async void load_lowres ()
> ```
> 
> Loads the low resolution media from the url.
> 
> ```c#
> public async void low_hires ()
> ```
> 
> Loads the high resolution media from the url.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public Gst.Element video
> ```
> 
> The Element storing the wanted video.
> 
> ```c#
> public Gst.Element video_hires
> ```
> 
> The Element storing the wanted video in high resolution.
> 
> ---
> 
> ## Image
> 
> ```c#
> public class Image : Media
> ```
> 
> A class storing a image from twitter.
> 
> Displayed in `MediaWidget` with zoom control.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ```c#
> public abstract async void load_lowres ()
> ```
> 
> Loads the low resolution media from the url.
> 
> ```c#
> public abstract async void low_hires ()
> ```
> 
> Loads the high resolution media from the url.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public Cairo.ImageSurface surface
> ```
> 
> The surface storing the image.
> 
> ```c#
> public Cairo.ImageSurface surface_hires
> ```
> 
> The surface storing the image in high resolution.
> 
> ---
> 
> ## Animation
> 
> ```c#
> public class Animation : Media
> ```
> 
> A class storing a animated gif from twitter.
> 
> Displayed in `MediaWidget` with playback indicator.
> 
> ### Creation Methods
> 
> ### Methods
> 
> ```c#
> public abstract async void load_lowres ()
> ```
> 
> Loads the low resolution media from the url.
> 
> ```c#
> public abstract async void low_hires ()
> ```
> 
> Loads the high resolution media from the url.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public Gdk.PixbufAnimation element
> ```
> 
> The animated pixbuf storing the image.
> 
> ```c#
> public Gdk.PixbufAnimation element_hires
> ```
> 
> The animated pixbuf storing the image in high resolution.
> 
> ---
> 
> ## Poll
> 
> ```c#
> public class Poll
> ```
> 
> ### Creation Methods
> 
> ```c#
> public Poll.from_json (Json.Node node)
> ```
> 
> Create a new poll object by parsing an given json node.
> 
> ### Methods
> 
> ```c#
> public void update.from_json ()
> ```
> 
> Updates the poll from the given json.
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public string id
> ```
> 
> The unique identifier for the poll object.
> 
> ```c#
> public PollOption[] options
> ```
> 
> All options for this poll.
> 
> ```c#
> public GLib.Date poll_end
> ```
> 
> The date and time when this poll is closed.
> 
> ```c#
> public bool closed
> ```
> 
> Indicates if it is still possible to vote on that poll.
> 
> ---
> 
> ## Notification
> 
> ```c#
> public class Notification
> ```
> 
> An structure saving information about an Notification to the system.
> 
> ### Creation Methods
> 
> ```c#
> public Notification (string title, string text)
> ```
> 
> Creates a generic notification.
> 
> ```c#
> public Notification.for_tweet (Tweet tweet)
> ```
> 
> Creates a notification for an tweet.
> 
> ### Methods
> 
> ### Signals
> 
> ### Fields
> 
> ```c#
> public string id
> ```
> 
> A unique identifier for this id.
> 
> ```c#
> public enum NotificationType type
> ```
> 
> The variant of this tweet. Used by `Utils.send_notification` on how to display them.
> 
> ```c#
> public string title
> ```
> 
> The title for the notification.
> 
> ```c#
> public string text
> ```
> 
> The text for the notification.
> 
> ### 
> 
> ---
> 
> # Structures
> 
> ## PollOption
> 
> ```c#
> public struct PollOption
> ```
> 
> A small structure storing informations for one poll option.
> 
> ### Fields
> 
> ```c#
> public int position
> ```
> 
> The position of this option in this poll
> 
> ```c#
> public string label
> ```
> 
> The label describing the option.
> 
> ```c#
> public int votes
> ```
> 
> How many votes this option got.
> 
> ---
> 
> # Enums
> 
> ## NotificationType
> 
> ```c#
> public enum NotificationType
> ```
> 
> ### Values
> 
> ```c#
> 'GENERIC' = 0
> ```
> 
> A generic notification.
> 
> As it is used primarily from the app, prioritize these notifications.
> 
> ```c#
> 'TWEET' = 1
> ```
> 
> A notification for an new tweet.
> 
> When there are only up to five new tweets in total, display all of them in separated notifications, otherwise group them in accounts, showing "x new tweets".
> 
> ---
> 
> ## TweetType
> 
> ```c#
> public enum TweetType
> ```
> 
> ### Values
> 
> ```c#
> 'GENERIC' = 0
> ```
> 
> A normal tweet.
> 
> ```c#
> 'RETWEET' = 1
> ```
> 
> The tweet is a retweet of another.
> 
> ```c#
> 'QUOTE' = 2
> ```
> 
> A quote of another tweet.
> 
> ---
> 
> ## TweetState
> 
> ```c#
> public enum TweetState
> ```
> 
> ### Values
> 
> ```c#
> 'GENERIC' = 0
> ```
> 
> Nothing interesting to see here, move along!
> 
> ```c#
> 'DELETED' = 1
> ```
> 
> This tweet was recently deleted.
> 
> ```c#
> 'HIDDEN_AUTHOR_BLOCKED' = 2
> ```
> 
> This tweet was hidden because the author was blocked.
> 
> ```c#
> 'HIDDEN_AUTHOR_MUTED' = 3
> ```
> 
> This tweet was hidden because the author was muted
> 
> ```c#
> 'HIDDEN_FILTERED' = 4
> ```
> 
> This tweet was hidden because the content was filtered.
> 
> ```c#
> 'HIDDEN_RETWEETER_BLOCKED' = 5
> ```
> 
> This tweet was hidden because the retweeter was blocked.
> 
> ```c#
> 'HIDDEN_RETWEETER_MUTED' = 6
> ```
> 
> This tweet was hidden because the retweeter was muted.
> 
> ```c#
> 'NSFW' = 7
> ```
> 
> This tweet contains media not suited for anyone.

So, the question is now: Is this an idea worth pursuing and where would I start with the implementation.

**Comment by IBBoard** [comment]
I'll start with the easy bit:

> So, the question is now: Is this an idea worth pursuing and where would I start with the implementation.

If you're going to do any API rework then it'll need to be on a branch and get merged later. The hardest part will be picking it all apart, though. There's a lot of interlinking between the C code, so you either have to start from the few outside bits and work in (where that's possible), or you've got to do it as a "big bang" implementation and break everything until you get the Vala working.

In general, I'd rather do a progressive replacement rather than a huge overhaul, though. I agree that the codebase is a bit odd in places and we should get rid of the C code wherever possible, but doing anything too significant in one go seems prone to introducing bugs or getting stuck for ages in a partially completed state.

Also, while a rewrite might make the code more accessible, it also takes time away from adding features and I'd have to relearn the code as well. What you've got is a core, but as I'm still finding new classes that I've never looked at before then I think there's more complexity than you'd expect at first glance. I think it might be more productive to find specific problems and ask questions and then rewrite that if necessary.


On the specifics: 

* Utils class 
   * We've already got one in "utils" (as well as the CbUtils.c that becomes Cb.Utils - no, I don't know why). Plus a load of dedicated functions for other things (TweetUtils for tweeting, ListUtils for list handling, etc)
   * Do we need to have a "get instance" method? Utils should be static where possible and not use an instance (which Vala seems to do by just having them in the namespace)
   * call_api is a nice idea, but chances are that you can't just do it with an API call string. There's normally multiple options and we need to supply them properly. Do we have API calls that should be moved to a util class? Yes. Should we replace librest calls with a single "call api"? No, I don't think it's possible.
   * What do we need the `send_notification` for? Is this just so we can create a notification from different places?
   * `reached_limit` is an interesting idea. But we can get different limits on different API calls. Also, I don't know how well it would work with multiple accounts.
   * OAuth fields - Cawbird's "shared by everyone" keys could go in utils, but it seems a little unnecessary to separate them from the librest proxy. All it saves is a few short strings in RAM. What does it gain us?

* User class
   * Generally looks sensible. But we need to handle the light-weight version for use with tweets where we don't get most of the info (see `CbUserIdentity`)
   * Will we ever populate all of the friends and followers of a user? Probably need the light-weight version at most.
   * But based on the previous two comments, do we need it at all? Or is it only used in one place (profile page) and we'll just build the UI from JSON results once and we don't need an object?

* Account
   * I guess an account is a user, so the inheritance makes sense.
   * Creating from a PIN probably shouldn't assume it's an int. It is technically an N digit numeric string.
   * I'm assuming users will be light-weight objects again, because we only use them to render the list of who is blocked and muted

* Filter
   * Seems fine

* TextEntity
   * I think we need a few more fields to handle all the situations. See `CbTextEntity` in `CbTypes.h` (although it's possible that we can reduce it and we've just never looked at it, but truncated links vs @-mentions is the obvious case of needing different behaviour)

* Tweet
   * `Tweet.from_id()` is fine in principle, but I don't know how much we call it and how much we'd hit API limits
   * ID being a string is a v2 API thing, isn't it? I vaguely remember complaining that it won't work for some sorting situations. And we'll need a LOT of API and database changes to support it.
   * We need to think through the TweetType with a single "source" object - will it work for all situations? I'm trying to think through "someone retweeted a quote tweet" etc.
   * Assuming the v2 API loads them, I'm assuming you can only have one poll with multiple options, not an array of them.
   * I guess we might as well store GLib Dates since we use them for generating the time delta anyway

* Thread
   * Trying to think this through. I *think* it will work, but it will need a lot of work to make sure we're loading tweets when we need them, not loading too many tweets, and giving a useful set of calls that we'll frequently use.
   * Your constructor is `Conversation`!
   * "call" methods should probably be "fetch" (call suggests invoking a method on them, not retrieving them)
   * `update_metrics` is going to burn through API calls

* Tweetline, List and Timeline
   * If there's no difference in methods, why differentiate?
   * "Tweetline" is an odd term and doesn't have the same meaning to most people. Twitter already [calls them all "timelines"](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/overview)
   * Is this a replacement for the widget or the data structure? Because currently a) we feed in messages one-by-one as if we're still streaming (and we *have* to support this, because we insert our own tweets and RTs), b) the "user stream" also lets us cross messages over between widgets (post a new tweet while looking at your profile? It appears. Delete one? It's gone from your home timeline as well. Like a tweet in a profile? It can get liked everywhere) and c) I don't know how well this would integrate with the GTK ListModel that backs all of the list views and duplicating that functionality seems pointless

* Media
   * I'm never sure whether it's better for an object to load itself from JSON or whether a central parsing class is better
   * We should have progress signals as well
   * Why do we have a MediaType if we're also sub-classing?
   * We need thumbnail width/height as well

* Video
   * Do we want to store the video as a Gst.Element? That seems like a memory sink. Better to just do as we do now and load it from the URL in the widget, because we're going to have buffering time anyway

* Image
   * No obvious notes

* Animation
   * Note that some (all?) GIFs come as MP4 these days because Twitter re-encodes them but we should still treat them as looping GIFs
* Notification type
   * Presumably needs a "DM" type as well at a minimum. There may be others.

* Poll
   * I'm assuming the v2 API will support these (I think I saw something somewhere, but it has been a while)
   * We need a question field
   * Do we need a "closed" if we've got "poll_end"? Better to check the time when doing the action rather than assuming `closed` is still correct

* PollOption
   * We've not got a way to show what the user voted for (assuming the API tells us that)

* Notification
   * Encapsulation is good, but do we have enough to bother encapsulating, or can we just pass three/four fields to the function?

* Tweet State
   * Would we be better off with something that we can bitmask? What if we blocked the author *and* the content is filtered?

**Comment by CodedOre** [comment]
So, I noticed there are a lot of inconsistency in here...

There are some things I already noticed myself (such as call_api with an string is worse than just giving it the ProxyCall) but not added to this document. This was basically just a place to think a few things about the backend through, not a 1:1 template to implement it later. And yes, I renamed "Conversation" to "Thread", hence the forgotten contructor...

So, considering the specifics:

> Utils class

Just ignore this...

*Actually, let's not ignore it entirely:*

> What do we need the send_notification for? Is this just so we can create a notification from different places?

This should work as a central manager which decides to push notification or just a summary depending on the situation, see `NotificationType`.

> reached_limit is an interesting idea. But we can get different limits on different API calls. Also, I don't know how well it would work with multiple accounts.

As far as I know there is one limit for each account. So, maybe this is better moved to Account.

> User class
> - Generally looks sensible. But we need to handle the light-weight version for use with tweets where we don't get most of the info (see `CbUserIdentity`)
> - Will we ever populate all of the friends and followers of a user? Probably need the light-weight version at most.
> - But based on the previous two comments, do we need it at all? Or is it only used in one place (profile page) and we'll just build the UI from JSON results once and we don't need an object?

Like with `CbUserIdentity` we also currently have `CbMiniTweet` as a small size object for Tweet, so my thought was that things like that could be one class which is only filled with what we need, but with the possibility to add details when needed.

But could also be a wrong approach.

> TextEntity
>   
> - I think we need a few more fields to handle all the situations. See `CbTextEntity` in `CbTypes.h` (although it's possible that we can reduce it and we've just never looked at it, but truncated links vs @-mentions is the obvious case of needing different behaviour)

Just looked at it over the public available fields with valadoc for now, so I might need to take a detailed look on the C code...

Even though I guess my current fields should be enough with maybe an enum describing what it is, but dunno.

> Tweet
> - `Tweet.from_id()` is fine in principle, but I don't know how much we call it and how much we'd hit API limits
> - ID being a string is a v2 API thing, isn't it? I vaguely remember complaining that it won't work for some sorting situations. And we'll need a LOT of API and database changes to support it.

Yes, API v2 will only give us strings as ids. But where would we sort tweets by their ids?

>   * We need to think through the TweetType with a single "source" object - will it work for all situations? I'm trying to think through "someone retweeted a quote tweet" etc.

Actually a good question. Since a retweet is basically just the previous tweet with an additional user...

I first would probably just created three Tweets with the retweet having the quote as origin which itself would have the original as origin.

> Thread  
> - Trying to think this through. I _think_ it will work, but it will need a lot of work to make sure we're loading tweets when we need them, not loading too many tweets, and giving a useful set of calls that we'll frequently use.

With the API v2 we could load all tweets from one thread with one search call, so this would be my plan: When we open a Tweet-Detail, just load any tweet in this thread and then load them from memory, hence the `call_all_tweets` and `call_new_tweets` methods.

> - `update_metrics` is going to burn through API calls

Could probably part of `call_`..., I mean `fetch_new_tweets` method, as we probably already need to check if there are new responses. Thinking about it, we don't need to different between `fetch_all` and `fetch_new`, because it will anytime be a `fetch_all`.

> Tweetline, List and Timeline  
> - If there's no difference in methods, why differentiate?
> - "Tweetline" is an odd term and doesn't have the same meaning to most people. Twitter already [calls them all "timelines"](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/overview)

A list and a timeline will probably have different calls, also a list has an additional banner, title and members.

However, they have a similar managing of the contained tweet, so I thought about having shared methods in an shared interface between them. This maybe also help with [#124](https://github.com/IBBoard/cawbird/issues/124) as we could just define a Tweetline as the startup point, no matter if it is the timeline or a list.

So, Tweetline because it is an shared interface and I did not have a better name for it...

> - Is this a replacement for the widget or the data structure? Because currently a) we feed in messages one-by-one as if we're still streaming (and we _have_ to support this, because we insert our own tweets and RTs), b) the "user stream" also lets us cross messages over between widgets (post a new tweet while looking at your profile? It appears. Delete one? It's gone from your home timeline as well. Like a tweet in a profile? It can get liked everywhere) and c) I don't know how well this would integrate with the GTK ListModel that backs all of the list views and duplicating that functionality seems pointless.

My intention for this was to be a data structure, as I would like to seperate data and UI, so when handyport is merged we can update the backend easily in the old branch as well.

> Media
> - Why do we have a MediaType if we're also sub-classing?

Because I forget to remove it when I went to sub-classing... Like I said previous, this was more an noteblock than an actual plan.

> Video  
> - Do we want to store the video as a Gst.Element? That seems like a memory sink. Better to just do as we do now and load it from the URL in the widget, because we're going to have buffering time anyway

I think it would be nice if we could pre-load media rather than loading it when you want to see it. It is really annoying to open a video and have to wait for high-res to load. But yes, this would need to be good or otherwise this would be a memory sink.

> Poll  
> - I'm assuming the v2 API will support these (I think I saw something somewhere, but it has been a while)
> - We need a question field

[It is, but it does not have a question field.](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/poll)

> - Do we need a "closed" if we've got "poll_end"? Better to check the time when doing the action rather than assuming `closed` is still correct

True.

> PollOption
> - We've not got a way to show what the user voted for (assuming the API tells us that)

I think I disagree. Even if it would just be a label next to the button, it would be possible to show.

> Notification
> - Encapsulation is good, but do we have enough to bother encapsulating, or can we just pass three/four fields to the function?

I think you need to specify this.

> Tweet State  
> - Would we be better off with something that we can bitmask? What if we blocked the author _and_ the content is filtered?

I think we currently also not have the option for multiple states and just go "The worse overides the bad". But having the opportunity to save multiple states is a good idea. Just have to look what the GLib equivalent would be.

**Comment by IBBoard** [comment]
>>    reached_limit is an interesting idea. But we can get different limits on different API calls. Also, I don't know how well it would work with multiple accounts.
>
> As far as I know there is one limit for each account. So, maybe this is better moved to Account.

Yes and no. Each account has a different limit *per API call*. So you've got 15 calls per 15 minutes for the home timeline, another limit for DMs, another limit for fetching details about a set of tweets, another for search…

> Like with CbUserIdentity we also currently have CbMiniTweet as a small size object for Tweet, so my thought was that things like that could be one class which is only filled with what we need, but with the possibility to add details when needed.
>
> But could also be a wrong approach.

It makes some sense. But I think it also risks having a lot of "is this property null and uncached?" checks. Or we have properties that trigger API calls and that feels like doing unexpected stuff, as well as being likely to cause poor responsiveness as an "is null" check triggers network requests.

> Yes, API v2 will only give us strings as ids. But where would we sort tweets by their ids?

Every part of the app that sorts tweets currently sorts by IDs. Partly because numbers are quick to sort. Partly because tweet IDs are "snowflakes" that are guaranteed unique, whereas two tweets could be posted at the same timestamp.

It feels ugly, but I remember mentioning it to someone from Twitter Dev and it looks like we're going to have to go for sort by date first and sort by ID as string second to get consistent ordering.

> With the API v2 we could load all tweets from one thread with one search call, so this would be my plan: When we open a Tweet-Detail, just load any tweet in this thread and then load them from memory, hence the call_all_tweets and call_new_tweets methods.

We can load lots of tweets in one call, but potentially not all of them on huge threads and busy conversations (search has a result count limit). Also, loading branches that the user never looks at is wasteful.

I'd be inclined to start by using the conversation ID to only find the replies in the current thread rather than trying to load the entire thread (currently we can't show useful threading for accounts like GitHub because they get mentioned so much that `to:github -from:github` brings back lots of irrelevant mentions)

> My intention for this was to be a data structure, as I would like to seperate data and UI, so when handyport is merged we can update the backend easily in the old branch as well.

Separating data structures from UI is good. And I can see that the threading model will help separate it and cache things. But my concern is that this makes a model that duplicates behaviour from the GTK ListModel and we can't avoid using ListModels, so we'd need to keep converting between the two. Unless this is a ListModel and we just set it for GTK to use and then have extra methods for our purposes?

> It is really annoying to open a video and have to wait for high-res to load. But yes, this would need to be good or otherwise this would be a memory sink.

I can't see a way around this. It happens even on Twitter Web. The only other option is that we do something smarter with the GStreamer widget that waits until some proportion of the video is cached (if it supports functions like that).

>> Poll: We need a question field
>
> It is, but it does not have a question field.

Okay. Shows how much attention I pay to polls on Twitter!

>>   PollOption
>>    *  We've not got a way to show what the user voted for (assuming the API tells us that)
>
> I think I disagree. Even if it would just be a label next to the button, it would be possible to show.
But we need some field to keep track of which option the user voted for. Assuming Twitter gives us that data.

---

Thinking through the classes and how a rewrite could go, I think it is going to be easiest to attack some of the GUI components first - CbMediaImageWidget and CbMediaVideoWidget. CbBundle only seems to be used in Vala code and in CbBundleHistory, so they could be converted. CbAvatarCache, CbSnippetManager and CbFilter only seems to be used in Vala code.

The hard ones appear to be CbTypes (which includes users, tweets and JSON parsing), CbTweet, CbMedia, CbMediaDownloader and CbUserStream, which are all interconnected and may need to be replaced in one go.

(This is all based on a quick bit of grepping)

It would be worth checking the commit log to see whether any of them were written in C because of issues with Vala, though. At least one was apparently because of memory leaks.

**Comment by CodedOre** [comment]
> It would be worth checking the commit log to see whether any of them were written in C because of issues with Vala, though. At least one was apparently because of memory leaks.

Have done a little research on my own following the git log for all C files, but other than the mention on `valac` you already found, I did not found anything more specific why he switched to C.
Guess he has done it once with `valac` in reason and then just switched the rest because some code was already in C...
But then it is still confusing to see him [ignoring all C files in the `.gitignore`](https://github.com/IBBoard/cawbird/pull/219).

Anyway, I am currently explore the current (slightly horrible) 1.1 API and the current code to make the vala-rewrite happen.
